/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
/**
 *
 * @author alfredo
 */
public class Inicio extends javax.swing.JFrame {
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelNuevaVenta = new javax.swing.JPanel();
        btnNuevaVenta = new javax.swing.JButton();
        PanelProductos = new javax.swing.JPanel();
        btnProductos = new javax.swing.JButton();
        PanelVentas = new javax.swing.JPanel();
        btnVentas = new javax.swing.JButton();
        PanelClientes = new javax.swing.JPanel();
        btnClientes = new javax.swing.JButton();
        PanelEmpresa = new javax.swing.JPanel();
        btnEmpresa = new javax.swing.JButton();
        PanelProveedores = new javax.swing.JPanel();
        btnProveedores = new javax.swing.JButton();
        PanelInicio = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelNuevaVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevaVenta.setBackground(new java.awt.Color(27, 66, 29));
        btnNuevaVenta.setFont(new java.awt.Font("Liberation Sans", 2, 36)); // NOI18N
        btnNuevaVenta.setForeground(new java.awt.Color(204, 204, 204));
        btnNuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo-producto.png"))); // NOI18N
        btnNuevaVenta.setText("NUEVA VENTA");
        btnNuevaVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevaVenta.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaVentaActionPerformed(evt);
            }
        });
        PanelNuevaVenta.add(btnNuevaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 300));

        getContentPane().add(PanelNuevaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 290, 300));

        PanelProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProductos.setBackground(new java.awt.Color(27, 66, 29));
        btnProductos.setFont(new java.awt.Font("Liberation Sans", 2, 36)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(204, 204, 204));
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/caja.png"))); // NOI18N
        btnProductos.setText("PRODUCTOS");
        btnProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProductos.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        PanelProductos.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 300));

        getContentPane().add(PanelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 290, 300));

        PanelVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVentas.setBackground(new java.awt.Color(27, 66, 29));
        btnVentas.setFont(new java.awt.Font("Liberation Sans", 2, 36)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(204, 204, 204));
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/grafico-de-barras.png"))); // NOI18N
        btnVentas.setText("VENTAS");
        btnVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVentas.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        PanelVentas.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 300));

        getContentPane().add(PanelVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 100, 290, 300));

        PanelClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClientes.setBackground(new java.awt.Color(27, 66, 29));
        btnClientes.setFont(new java.awt.Font("Liberation Sans", 2, 36)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(204, 204, 204));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/kyc.png"))); // NOI18N
        btnClientes.setText("CLIENTES");
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientes.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        PanelClientes.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 300));

        getContentPane().add(PanelClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 290, 300));

        PanelEmpresa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEmpresa.setBackground(new java.awt.Color(27, 66, 29));
        btnEmpresa.setFont(new java.awt.Font("Liberation Sans", 2, 36)); // NOI18N
        btnEmpresa.setForeground(new java.awt.Color(204, 204, 204));
        btnEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/edificio-de-oficinas.png"))); // NOI18N
        btnEmpresa.setText("EMPRESA");
        btnEmpresa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmpresa.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpresaActionPerformed(evt);
            }
        });
        PanelEmpresa.add(btnEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 300));

        getContentPane().add(PanelEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 430, 290, 300));

        PanelProveedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProveedores.setBackground(new java.awt.Color(27, 66, 29));
        btnProveedores.setFont(new java.awt.Font("Liberation Sans", 2, 36)); // NOI18N
        btnProveedores.setForeground(new java.awt.Color(204, 204, 204));
        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/repartidor.png"))); // NOI18N
        btnProveedores.setText("PROVEEDOR");
        btnProveedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProveedores.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        PanelProveedores.add(btnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 300));

        getContentPane().add(PanelProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 290, 300));

        PanelInicio.setBackground(new java.awt.Color(27, 66, 29));
        PanelInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        PanelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo.png"))); // NOI18N
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        PanelInicio.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 90));

        btnCerrarSesion.setBackground(new java.awt.Color(27, 66, 29));
        btnCerrarSesion.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(204, 204, 204));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/esquema-del-boton-de-flecha-cuadrada-de-inicio-de-sesion.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        PanelInicio.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 230, 90));

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("SISTEMA DE VENTAS ALOGAR");
        PanelInicio.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 940, 90));

        getContentPane().add(PanelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 90));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Fondo Virtual para Zoom Ondas Il.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel1.setPreferredSize(new java.awt.Dimension(1380, 700));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        this.dispose();
        Login lg = new Login();
        lg.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaVentaActionPerformed
        this.dispose();
        NuevaVenta Nv = new NuevaVenta();
        Nv.setVisible(true);
    }//GEN-LAST:event_btnNuevaVentaActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        this.dispose();
        Productos Pro = new Productos();
        Pro.setVisible(true);
        Pro.ListarProductos();
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        this.dispose();
        Proveedores Pv = new Proveedores();
        Pv.setVisible(true);
        Pv.ListarProveedor();
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        this.dispose();
        Ventas Vn = new Ventas();
        Vn.setVisible(true);
        Vn.ListarVentas();
        Vn.ListarProductosVentas();
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        this.dispose();
        Clientes Cl = new Clientes();
        Cl.setVisible(true);
        Cl.ListarCliente();
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpresaActionPerformed
        this.dispose();
        Empresa Em = new Empresa();
        Em.setVisible(true);
        Em.ListarConfig();
    }//GEN-LAST:event_btnEmpresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelClientes;
    private javax.swing.JPanel PanelEmpresa;
    private javax.swing.JPanel PanelInicio;
    private javax.swing.JPanel PanelNuevaVenta;
    private javax.swing.JPanel PanelProductos;
    private javax.swing.JPanel PanelProveedores;
    private javax.swing.JPanel PanelVentas;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEmpresa;
    private javax.swing.JButton btnNuevaVenta;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
