/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.ProductosVentas;
import Modelo.Venta;
import Modelo.VentaDao;
import Reportes.ExcelProductosVentas;
import Reportes.ExcelVentas;
import java.awt.Desktop;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Comparator;
import java.util.Date;
import java.util.List;
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.swing.table.DefaultTableModel;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.printing.PDFPageable;

/**
 *
 * @author alfredo
 */
public class Ventas extends javax.swing.JFrame {
    DefaultTableModel modelo = new DefaultTableModel();
    VentaDao VDao = new VentaDao();
    Date fechaVenta = new Date();
    String fechaActual = new SimpleDateFormat("yyyy-MM-dd").format(fechaVenta);

    
    public Ventas() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtIdVentas.setVisible(false);
    }
    
    public void ListarVentas() {
        List<Venta> ListarVenta = VDao.ListarVentas();
        modelo = (DefaultTableModel) TablaVentas.getModel();
        Object[] ob = new Object[3];
        for (int i = 0; i < ListarVenta.size(); i++) {
            ob[0] = ListarVenta.get(i).getId();
            ob[1] = ListarVenta.get(i).getTotal();
            ob[2] = ListarVenta.get(i).getFecha_venta();
            modelo.addRow(ob);
        }
        TablaVentas.setModel(modelo);
    }
    
    public void ListarProductosVentas() {
        List<ProductosVentas> ListarProductosVentas = VDao.ListarProductosVentas();
        modelo = (DefaultTableModel) TableProductosVentas.getModel();
        Comparator<ProductosVentas> cantidadComparator = Comparator.comparingInt(ProductosVentas::getCantidad).reversed();
        ListarProductosVentas.sort(cantidadComparator);
        modelo.setRowCount(0);
        Object[] ob = new Object[3];
        for (int i = 0; i < ListarProductosVentas.size(); i++) {
            ob[0] = ListarProductosVentas.get(i).getProductos();
            ob[1] = ListarProductosVentas.get(i).getCantidad();
            ob[2] = ListarProductosVentas.get(i).getPrecio_producto();
            modelo.addRow(ob);
        }
        TableProductosVentas.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdVentas = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaVentas = new javax.swing.JTable();
        btnPdfVentas = new javax.swing.JButton();
        btnExcleVentas = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableProductosVentas = new javax.swing.JTable();
        PanelInicio = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdVentasActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 230, 10, -1));

        TablaVentas.setBackground(new java.awt.Color(204, 204, 204));
        TablaVentas.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        TablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TOTAL", "FECHA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Short.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaVentas.setRowHeight(30);
        TablaVentas.setShowHorizontalLines(true);
        TablaVentas.setShowVerticalLines(true);
        TablaVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaVentasMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TablaVentas);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 680, 270));

        btnPdfVentas.setBackground(new java.awt.Color(204, 204, 204));
        btnPdfVentas.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        btnPdfVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/abrir-folleto-pdf.png"))); // NOI18N
        btnPdfVentas.setText("Exportar Boleta PDF");
        btnPdfVentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnPdfVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPdfVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPdfVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdfVentasActionPerformed(evt);
            }
        });
        getContentPane().add(btnPdfVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 290, 130));

        btnExcleVentas.setBackground(new java.awt.Color(204, 204, 204));
        btnExcleVentas.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        btnExcleVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/sobresalir.png"))); // NOI18N
        btnExcleVentas.setText("Generar Excel de Ventas");
        btnExcleVentas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnExcleVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcleVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcleVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcleVentasActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcleVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 290, 130));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/sobresalir.png"))); // NOI18N
        jButton2.setText("Generar Excel Productos");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 250, 310, 130));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/impresora.png"))); // NOI18N
        jButton4.setText("Imprimir Boleta");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 110, 310, 130));

        TableProductosVentas.setBackground(new java.awt.Color(204, 204, 204));
        TableProductosVentas.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        TableProductosVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCTO", "CANTIDAD", "PRECIO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableProductosVentas.setRowHeight(30);
        TableProductosVentas.setShowHorizontalLines(true);
        TableProductosVentas.setShowVerticalLines(true);
        jScrollPane1.setViewportView(TableProductosVentas);
        if (TableProductosVentas.getColumnModel().getColumnCount() > 0) {
            TableProductosVentas.getColumnModel().getColumn(0).setPreferredWidth(200);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 1330, 330));

        PanelInicio.setBackground(new java.awt.Color(27, 66, 29));
        PanelInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        PanelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo.png"))); // NOI18N
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        PanelInicio.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 100));

        btnCerrarSesion.setBackground(new java.awt.Color(27, 66, 29));
        btnCerrarSesion.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(204, 204, 204));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/esquema-del-boton-de-flecha-cuadrada-de-inicio-de-sesion.png"))); // NOI18N
        btnCerrarSesion.setText("Volver A Inicio");
        btnCerrarSesion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        PanelInicio.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 230, 100));

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("VENTAS ALOGAR");
        PanelInicio.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 940, 100));

        getContentPane().add(PanelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 100));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Fondo Virtual para Zoom Ondas Il.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel1.setPreferredSize(new java.awt.Dimension(1380, 700));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        this.dispose();
        Inicio In = new Inicio();
        In.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnPdfVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdfVentasActionPerformed
        try {
            int id = Integer.parseInt(txtIdVentas.getText());
            File file = new File(System.getProperty("user.home") + "/Escritorio/boleta" + id + '-' + fechaActual + ".pdf");
            Desktop.getDesktop().open(file);
        } catch (IOException ex) {
            Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPdfVentasActionPerformed

    private void txtIdVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdVentasActionPerformed

    private void TablaVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaVentasMouseClicked
        int fila = TablaVentas.rowAtPoint(evt.getPoint());
        txtIdVentas.setText(TablaVentas.getValueAt(fila, 0).toString());
    }//GEN-LAST:event_TablaVentasMouseClicked

    private void btnExcleVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcleVentasActionPerformed
        ExcelVentas.reporte();
    }//GEN-LAST:event_btnExcleVentasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ExcelProductosVentas.reporte();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    try {
        int id = Integer.parseInt(txtIdVentas.getText());
        File file = new File(System.getProperty("user.home") + "/Escritorio/Boletas/boleta" + id + ".pdf");
        PDDocument document = PDDocument.load(file);
        PrinterJob job = PrinterJob.getPrinterJob();

        // Obtener todas las impresoras disponibles en el sistema
        PrintService[] printServices = PrintServiceLookup.lookupPrintServices(null, null);
        PrintService namedPrinter = null;
        for (PrintService service : printServices) {
            if (service.getName().equals("HP_Smart_Tank_530_series_1FC5D6@HP6C02E01FC5D6.local")) {
                namedPrinter = service;
                break;
            }
        }

        if (namedPrinter != null) {
            // Configurar la impresora para la impresión
            job.setPrintService(namedPrinter);
            job.setPageable(new PDFPageable(document));
            job.print();
        } else {
            System.out.println("No se encontró la impresora con el nombre especificado.");
        }

        document.close();
    } catch (IOException | PrinterException e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelInicio;
    private javax.swing.JTable TablaVentas;
    private javax.swing.JTable TableProductosVentas;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnExcleVentas;
    private javax.swing.JButton btnPdfVentas;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField txtIdVentas;
    // End of variables declaration//GEN-END:variables
}
